{% set name = "momepy" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/momepy-{{ version }}.tar.gz
  sha256: 413ed9221dc4b2190621f8cb37789f09ea882f7e81dfbffd5731a22da6e61bab
  patches:
    - patches/numpy2_fix.patch
    # Test contains incorrect dependency version check condition and precision tolerance.
    - patches/fix_test_alignment.patch
    # Changes package's usage of geopandas' deprecated query_bulk() API with query(), removed in geopandas>=1.0.
    # Can be uncommented to release the upper bound constraint on geopandas
    #- patches/change_query_bulk_to_query.patch

build:
  skip: true  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - toml
    - wheel
  run:
    - python
    # Added upper bound as the package uses an API removed in geopandas 1.0. Upper bound can be lifted
    # with the change_query_bulk_to_query patch.
    - geopandas >=0.12.0,<1.0
    - libpysal >=4.6.0
    - networkx >=2.7
    - packaging 
    - pandas !=1.5.0
    - shapely >=2
    - tqdm >=4.63.0

  run_constrained:
    # geopandas file io APIs uses fiona.path in tests, removed from fiona 1.10. while these are only used
    # by test, it is indicative of the environment expectation from the project at this point.
    - fiona <1.10

test:
  source_files:
    - momepy/tests
  imports:
    - momepy
  commands:
    - pip check
    - pytest -vv momepy/tests
  requires:
    - pip
    - pytest
    - inequality
    - mapclassify
    - numba
    - esda

about:
  home: https://docs.momepy.org
  summary: Urban Morphology Measuring Toolkit
  description: |
    Momepy is a library for quantitative analysis of urban form - urban morphometrics. 
    It is part of PySAL (Python Spatial Analysis Library) and is built on top of GeoPandas, 
    other PySAL modules, and networkX.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://docs.momepy.org
  dev_url: https://github.com/pysal/momepy

extra:
  recipe-maintainers:
    - psteyer
