{% set name = "momepy" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/momepy-{{ version }}.tar.gz
  sha256: 413ed9221dc4b2190621f8cb37789f09ea882f7e81dfbffd5731a22da6e61bab

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: True  # [py>310]

requirements:
  host:
    - python
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python
    - geopandas >=0.12.0
    - libpysal >=4.6.0
    - networkx >=2.7
    - packaging
    - pandas !=1.5.0
    - shapely >=2
    - tqdm >=4.63.0

test:
  imports:
    - momepy
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Urban Morphology Measuring Toolkit
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
